---
- hosts: localhost
  tasks:
  - name: Lookup variable in Conjur
    debug:
      msg: "{{ lookup('conjur_variable', 'data/vault/at-ansible-safe/Operating System-WinDomain-target.cybr.com-ansible-svc-acc/password') }}"
